### PR TITLE
Remove additional packages

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by dhermes** [comment]
Where's it going?

**Comment by jonparrott** [comment]
https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2
and
https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib

**Comment by jonparrott** [comment]
Travis failed due to a new pylint release that's catching my bad code. Will fix that separately, then rebase, then merge.

**Comment by dhermes** [comment]
OK. LGTM if these remains a DELETES-ONLY PR. Ping me otherwise?

**Comment by jonparrott** [comment]
Yes, this will remain delete only.

**Pull request merged**
