### PR TITLE
Check for project_id envvar before warning

### PR DESCRIPTION
**Pull request by JacobHayes**
Resolves GoogleCloudPlatform/google-auth-library-python#221

### CODE REVIEW

**Comment by jonparrott** [comment]
This kind of indicates to me that we should remove the individual warnings and just warn in default()?

**Comment by JacobHayes** [comment]
Agreed. The messages were _just_ different enough that I didn't tackle that originally. Would you prefer to make the message the same (ie: not reporting where the `credentials` came from) or something like adding a name to [`checkers`](https://github.com/JacobHayes/google-auth-library-python/blob/f42d53519b6ecf2a4ce235f3c04e34e54b6fa9da/google/auth/_default.py#L281) to fill into the message? Ex:

```python
    checkers = {  # or tuple of two-tuples
        os.environ.get(environment_vars.CREDENTIALS): _get_explicit_environ_credentials,
        'Cloud SDK Credentials': _get_gcloud_sdk_credentials,
        'App Engine metadata service': _get_gae_credentials,
        'Compute Engine metadata service': lambda: _get_gce_credentials(request),
    }
```

**Comment by jonparrott** [comment]
> prefer to make the message the same (ie: not reporting where the credentials came from)

That would be fine. :)

**Comment by JacobHayes** [comment]
Any ideas on fixing the coverage test?

**Comment by jonparrott** [comment]
Write a test that mocks all the checkers to return no project?

**Comment by jonparrott** [comment]
Thanks for doing this, @JacobHayes!

**Comment by JacobHayes** [comment]
Absolutely; thanks for the guidance!

**Pull request merged**
